FIND_PATH(SDL2_IMAGE_INCLUDE_DIR SDL2/SDL_image.h
  HINTS ${LIBS}
  PATH_SUFFIXES include i686-w64-mingw32/include x86_64-w64-mingw32/include
  PATHS ~/Library/Frameworks /Library/Frameworks /usr/local/include /usr/include /opt
)

GET_FILENAME_COMPONENT(SDL2_IMAGE_DIR ${SDL2_IMAGE_INCLUDE_DIR} DIRECTORY)

IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
  FIND_LIBRARY(SDL2_IMAGE_LIBRARY_TEMP
    NAMES SDL2_image
    HINTS ${LIBS}/SDL2_image
    PATH_SUFFIXES lib64 lib lib/x64 x86_64-w64-mingw32/lib
    PATHS  /sw /opt/local /usr/local /opt/csw /opt
  )
ELSE(CMAKE_SIZEOF_VOID_P EQUAL 8)
  FIND_LIBRARY(SDL2_IMAGE_LIBRARY_TEMP
    NAMES SDL2_image
    HINTS ${LIBS}/SDL2_image
    PATH_SUFFIXES lib lib/x86 i686-w64-mingw32/lib
    PATHS /sw /opt/local /usr/local /opt/csw /opt
  )
ENDIF(CMAKE_SIZEOF_VOID_P EQUAL 8)

IF(SDL2_IMAGE_LIBRARY_TEMP)
  SET(SDL2_IMAGE_LIBRARY ${SDL2_IMAGE_LIBRARY_TEMP} CACHE STRING "Where the SDL2_image Library can be found")
  SET(SDL2_IMAGE_LIBRARY_TEMP "${SDL2_IMAGE_LIBRARY_TEMP}" CACHE INTERNAL "")
ELSE(SDL2_IMAGE_LIBRARY_TEMP)
  MESSAGE(FATAL_ERROR "Could not find the libs for SDL2_image. Make sure the library folders have the correct names. SDL2_IMAGE_LIBRARY_TEMP was not set.")
ENDIF(SDL2_IMAGE_LIBRARY_TEMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_IMAGE REQUIRED_VARS SDL2_IMAGE_INCLUDE_DIR)
